### ISSUE TITLE
Build for firefox

### ISSUE THREAD

**Issue by Nighteye841228** [tategakibunko/nehan#5]
Hello I'm a firefox user, and I wanna know is there any possibilities to build the .ts file to make it fore firefox extension or use it like greasemonkey?

**Comment by tategakibunko** [comment]
I don't know much about greasemoney,  but you can use webpack to build the ts project and turn it into js, and then import it into greasemonkey.

Alternatively, it may be easier to use [nehan-player](https://github.com/tategakibunko/nehan-player), which is web-component of nehan.

CDN url is https://cdn.jsdelivr.net/npm/nehan-player/dist/nehan-player.min.js
